# Generated by Django 4.2.4 on 2024-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=40)),
                ('vaccine_name', models.CharField(max_length=20, null=True)),
                ('dose_no', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_vaccianatio', models.DateField(null=True)),
            ],
        ),
    ]
